apiVersion: v1
kind: BuildConfig
metadata:
  name: multi-rpm-imagesource
  labels:
    app: multi-rpm-imagesource
spec:
  output:
    to:
      kind: ImageStreamTag
      name: multi-rpm-imagesource:latest
  source:
    git:
      ref: master
      uri: http://gogs.rpm-jenkins-mock.svc.cluster.local:3000/developer/demo_container.git
    images:
    - from:
        kind: ImageStreamTag
        name: multi-rpm-imagesource-repo:latest
      paths:
      - destinationDir: ./
        sourcePath: /yum_repo
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: centos:7
