apiVersion: v1
kind: BuildConfig
metadata:
  name: multi-rpm-imagesource-pipeline
  labels:
    app: multi-rpm-imagesource
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "multi-rpm-imagesource", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  source:
    type: Git
    git:
      uri: "http://gogs.rpm-jenkins-mock.svc.cluster.local:3000/developer/app-multi-rpm-imagesource.git"
  strategy:
    jenkinsPipelineStrategy: {}
    type: JenkinsPipeline
  triggers:
  - generic:
      secret: 0123abcd
    type: Generic
