apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: single-rpm
  name: single-rpm
spec:
  output:
    to:
      kind: ImageStreamTag
      name: single-rpm:latest
  source:
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: centos:7
    type: Docker
