apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: multi-rpm-submodules
  name: multi-rpm-submodules
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'multi-rpm-submodules:latest'
  source:
    git:
      ref: master
      uri: http://gogs.rpm-docker-build.svc.cluster.local:3000/developer/demo_container_submodules.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: centos:7
  triggers:
  - generic:
      secret: 0123abcd
    type: Generic
