apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: single-rpm
  name: single-rpm
spec:
  output:
    to:
      kind: ImageStreamTag
      name: single-rpm:latest
  source:
    git:
      ref: master
      uri: http://gogs.rpm-docker-build.svc.cluster.local:3000/developer/hello.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: centos:7
      noCache: true
    type: Docker
  triggers:
  - generic:
      secret: 0123abcd
    type: Generic
