srpm: clean
	mkdir -p build/SOURCES
	tar --exclude-vcs --exclude='./build' --transform "s;^./;hello/;" \
		-zcvf build/SOURCES/hello.tar.gz ./
	rpmbuild --define "_topdir `pwd`/build/" --undefine "dist" \
		-bs hello.spec

clean:
	rm -rf build
