apiVersion: v1
kind: BuildConfig
metadata:
  name: hello-container
  labels:
    app: hello-container
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'hello-container:latest'
  source:
    type: Binary
    dockerfile: |
      FROM centos:7
      COPY *.rpm /tmp/rpms/
      RUN yum install -y /tmp/rpms/*.rpm && \
          yum clean all -y
      RUN mkdir -p /var/www/cgi-bin && \
          ln -s /usr/bin/hello /var/www/cgi-bin/hello && \
          echo '<html><head><meta http-equiv="refresh" content="0; url=cgi-bin/hello"></head></html>' > /var/www/index.html
      WORKDIR /var/www
      USER 1001
      EXPOSE 8000
      ENTRYPOINT ["/usr/bin/python", "-m", "CGIHTTPServer", "8000"]
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: centos:7
