apiVersion: v1
kind: BuildConfig
metadata:
  name: demo-container
  labels:
    app: demo-container
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'demo-container:latest'
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: centos:7
