apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: jenkins-slave-rpmbuilder-centos7-rebuild
spec:
  schedule: "0 0 * * Mon"
  jobTemplate:
    spec:
      backoffLimit: 3
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            parent: jenkins-slave-rpmbuilder-centos7-rebuild
        spec:
          containers:
          - name: jenkins-slave-rpmbuilder-centos7-rebuild
            image: openshift/origin
            command: ["oc",  "start-build", "jenkins-slave-rpmbuilder-centos7"]
          restartPolicy: Never
          serviceAccount: jenkins
